apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: redis-cache-pvc
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 2Gi
    storageClassName: standard
